### ISSUE TITLE
Link project repository to Zenodo

### ISSUE THREAD

**Issue by matthewfeickert** [peterridolfi/Pyhf-to-Combine-converter#3]
To ensure that the Fellow project has a nice DOI associated with it, it would be great to also link the project to [Zenodo](https://zenodo.org/).

[![zenodo_instructions](https://user-images.githubusercontent.com/5142394/184678979-4ab8b1dd-0d87-47b6-bbce-6e0d893aa0d8.png)](https://zenodo.org/account/settings/github/)

This can be done under https://zenodo.org/account/settings/github/ once you have an account and then once you make a [GitHub release](https://github.com/peterridolfi/Pyhf-to-Combine-converter/releases) (not just a tag, but a release) Zenodo will automatically grab the snapshot of the repository at that release and archive it on Zenodo and mint a DOI for it. :+1: Here are full instructions: https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content

As an example, here are `pyhf`'s and `cabinetry`'s

* [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.1169739.svg)](https://doi.org/10.5281/zenodo.1169739)
* [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.4742752.svg)](https://doi.org/10.5281/zenodo.4742752)

**Comment by peterridolfi** [comment]
Done
