### ISSUE TITLE
Specify lower bound of pyhf API more

### ISSUE THREAD

**Issue by matthewfeickert** [peterridolfi/Pyhf-to-Combine-converter#5]
At the moment the lower bound on `pyhf` is 

https://github.com/peterridolfi/Pyhf-to-Combine-converter/blob/2d154ad73ab460b8a6b7512f1cc8df5fb102ff0a/pyproject.toml#L27

However, given some of the changes in API and bug fixes I would suggest making that

```
"pyhf>=0.6.3"
```

as that will give greater stability.

**Comment by peterridolfi** [comment]
Done
